### PR TITLE
Issue #307

### PR DESCRIPTION
**Pull request by geirkairam**
Hide Tasks marked with "h:1"

### CODE REVIEW

**Comment by benrhughes** [comment]
Hi,
Thanks for the pull request. Unfortunately I'm not going to accept it - without very good reason, we don't introduce syntax changes that are not supported by the main todo.txt project.

The best way to make sure your PR will be accepted is to raise an issue and have one of the maintainers OK the work before you proceed.

Thanks for your interest in the project.

Cheers,

Ben

**Comment by geirkairam** [comment]
What did I get wrong in your answer for Issue #307 "If someone submits a pull request in the future I'll accept it" ?

**Comment by benrhughes** [comment]
Ugh, sorry mate - short term memory loss! I've had a few people submit PRs
without checking, and I'd forgotten that we'd had that conversation! I'll
merge it in when I'm back on my computer.

Cheers, and again, apologies,

Ben

**Comment by geirkairam** [comment]
Ok, thanks. Let me know if I need to improve something to get this accepted :)

**Pull request merged**
