### PR TITLE
fixing #349

### PR DESCRIPTION
**Pull request by keighrim**
`DONE` and `-DONE` filters had bug that they not only check completeness of a task but also check substring match test.

### CODE REVIEW

**Comment by benrhughes** [comment]
Thanks :)

**Comment by shulist** [comment]
In testing 3.3.1 (beta) I have found that the DONE filter seems not to work. While the -DONE filter works just fine.

**Comment by sergeevabc** [comment]
Why do I download the latest binary that includes this fix?

**Comment by shulist** [comment]
> 
> 
> Why do I download the latest binary that includes this fix?

I am assuming you actually wanted to ask "Where do I download the latest  binary?" The current version can be had by going to the **Code** tab above and clicking on the link about halfway down the right column. However [here is the link.](https://github.com/benrhughes/todotxt.net/pull/359#issuecomment-832470733)

**Pull request merged**
