### PR TITLE
Pass MainWindowViewModel to IntellisenseTextbox using dependency property.

### PR DESCRIPTION
**Pull request by eugenezhub**
Pass MainWindowViewModel to IntellisenseTextbox using dependency property. Issue #66

### CODE REVIEW

**Comment by benrhughes** [comment]
Cheers!

**Comment by mjdescy** [comment]
This commit causes a runtime error for me. IntellisenseTextBox.cs can't get a reference to MainWindowViewModel.TaskList.

**Comment by eugenezhub** [comment]
Sorry, I'll look at it tonight. Maybe I forgot to check something in.

**Comment by eugenezhub** [comment]
Mike, are you still getting it or did your latest commit fixed it?

**Comment by mjdescy** [comment]
My last commit did not fix it. It fixed an unrelated bug.

I think that the reference to MainWindowViewModel doesn't belong in IntellisenseTextBox.cs at all, really. It would be best to set the reference to the TaskList outside the class, in XAML or in code-behind. That would make the IntellisenseTextBox.cs more self-contained.

The way I originally got the reference to the TaskList was a total hack. I was so excited to get the code working, that I just pushed the commit.

**Comment by benrhughes** [comment]
Sorry guys, I should have thought about this a bit more closely before I
merged it.

I think Mike's right in that IntellisenseTextbox shouldn't need
MainWindowViewModel - in general a view model is only used for the
associated view (in this case MainWindow).

I'm on holidays and can't really remember how IntellisenseTextbox is set
up, but following general MVVM principles, I'd think that you'd have a
TaskList property on IntellisenseTextboxViewModel and then bind the
IntellisenseTextbox ListBox's Source to that property.

Alternatively (eg if we don't have an IntellisenseTextboxViewModel) you
could add a TaskList dependency property to IntellisenseTextbox and set it
in containing xaml.

Hope that makes sense.

Cheers,

Ben

**Comment by mjdescy** [comment]
It appears that we can't set the property in XAML unless we create an attached property. Perhaps the best approach is to make IntellisenseTextBox.TaskList a (normal) public property and set it in the windows' codebehind, as follows. This code works in the main window, but we'd need to make it work in the Filters window, too.

```c#
    private void Window_Loaded(object sender, RoutedEventArgs e)
    {
        ViewModel = new MainWindowViewModel(this);
        DataContext = ViewModel;
        taskText.TaskList = ViewModel.TaskList;
    }
```

**Comment by eugenezhub** [comment]
Sorry about the commit. I tried to pass just TaskList from XAML at first, but I couldn't make it work, which is why I went for MainWIndowViewModel instead. I didn't realize it was also usesd in FilterDialog.
Not sure what the best way to make it work for both MainWindow and FilterDialog. We don't have access to MainWindowViewModel in FilterDialog. And I guess we don't really want it.
If we could extract logic to construct TaskList, we could just reuse it in both windows. Don't know what the best approach should be.

**Comment by mjdescy** [comment]
I will take a look at this again tomorrow sometime. I think we can pass the instance of the main window view model to the child windows in their constructors. Then we can set the properties for the task list item there.

**Comment by eugenezhub** [comment]
Well, then we expose MainWindowViewModel to the child components, if I understand it correctly. Would this be different from using DependencyProperty for the MainWindowViewModel in the child components?
Let me know if you want me to rollback my change and submit a new pull request or if you can just undo the merge for my original pull request.

**Comment by benrhughes** [comment]
My 2c,
Each control should have a view model, which is constructed with only the
data it requires. If FilterDialog needs TaskList, then MainWindowViewModel
should construct a FilterDialogViewModel, passing in TaskList to the
constructor. FilterDialogViewModel should be set as the DataContext on
FilterDialog.

Continuing the pattern, FilterDialogViewModel should create an
IntellisenseTextboxViewModel (passing in TaskList) and set it as
IntellisenseTextbox's DataContext.

Obviously it's a bit of a judgement call as to whether it's worth MVVMing
everything as we go, and I'm happy for us to take small steps in the right
direction without having to get it all right first up. But I think it's
worth knowing/agreeing on the end goal so we know we're headed in the right
direction.

Cheers,

Ben

**Comment by mjdescy** [comment]
@benrhughes My last commit was pragmatic: fix the bug and get us another step closer to MVVM by using bindings to pass the TaskList to IntellisenseTextBox. Making a FilterViewModel was my first thought, but I wasn't sure what the best way to do that just yet.

I completely agree with you on how it should be modeled. In the end, I would like to see a ViewModel for each window, and command and data binding used throughout the app. I am just not at the level with WPF and MVVM yet where I am comfortable doing all the refactoring. 

I'd like to plan out the refactor and implement it piecemeal (in dev) sometime after the next production release. A refactor should bump the major version number and allow us to do new things (additional features) or better things (more unit tests, better filtering).

**Pull request merged**
